mov_time : 5.0  # movement time
tar_pose :
  r_hip_yaw : 0.000000
  l_hip_yaw : -0.000000
  r_hip_roll : -0.000000
  l_hip_roll : -0.000000
  r_hip_pitch : -26.90
  l_hip_pitch : 26.90
  r_knee : 53.80
  l_knee : -53.80
  r_ank_pitch : 26.90
  l_ank_pitch : -26.90
  r_ank_roll : -0.000000
  l_ank_roll : -0.000000
