# weight_value

weight_value :
  1  : 1.0    # r_hip_yaw
  2  : 1.0    # l_hip_yaw
  3  : 1.0    # r_hip_roll
  4  : 1.0    # l_hip_roll
  5  : 1.0    # r_hip_pitch
  6  : 1.0    # l_hip_pitch
  7  : 1.0    # r_knee
  8  : 1.0    # l_knee
  9  : 1.0    # r_ank_pitch
  10 : 1.0    # l_ank_pitch
  11 : 1.0    # r_ank_roll
  12 : 1.0    # l_ank_roll
