l_ank_pitch:
  fb_d_joint_position: 0.003
  fb_i_joint_position: 0.002
  fb_p_joint_position: 3
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_ank_roll:
  fb_d_joint_position: 0.001
  fb_i_joint_position: 0.0004
  fb_p_joint_position: 3
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_pitch:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_roll:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 2.5
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_yaw:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_knee:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_ank_pitch:
  fb_d_joint_position: 0.003
  fb_i_joint_position: 0.002
  fb_p_joint_position: 3
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_ank_roll:
  fb_d_joint_position: 0
  fb_i_joint_position: 0
  fb_p_joint_position: 3
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_pitch:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_roll:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 2.5
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_yaw:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_knee:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 4
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0