l_ank_pitch:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 15
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_ank_roll:
  fb_d_joint_position: 0.001
  fb_i_joint_position: 0.001
  fb_p_joint_position: 15
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_pitch:
  fb_d_joint_position: 0.1
  fb_i_joint_position: 0.01
  fb_p_joint_position: 220
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_roll:
  fb_d_joint_position: 0.1
  fb_i_joint_position: 0.001
  fb_p_joint_position: 35
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_hip_yaw:
  fb_d_joint_position: 0
  fb_i_joint_position: 0
  fb_p_joint_position: 5
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
l_knee:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 50
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_ank_pitch:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 15
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_ank_roll:
  fb_d_joint_position: 0.001
  fb_i_joint_position: 0.001
  fb_p_joint_position: 15
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_pitch:
  fb_d_joint_position: 0.1
  fb_i_joint_position: 0.01
  fb_p_joint_position: 220
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_roll:
  fb_d_joint_position: 0.1
  fb_i_joint_position: 0.001
  fb_p_joint_position: 35
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_hip_yaw:
  fb_d_joint_position: 0
  fb_i_joint_position: 0
  fb_p_joint_position: 5
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0
r_knee:
  fb_d_joint_position: 0.01
  fb_i_joint_position: 0.001
  fb_p_joint_position: 50
  fb_p_torque: 0
  ff_joint_velocity: 0
  ff_torque: 0